# Amount of hearts after unban.
unban-hearts: 4
# Maximum amount of hearts. 0 = No Limit
max-hearts: 100
# If enabled, players with max hearts will be highlighted after they get hit.
highlight-maxed: true
unban-anchor:
  material: 'beacon'
  recipe:
    shape:
      - ' G '
      - 'DBD'
      - ' G '
    ingredients:
      G: 'gold_ingot'
      D: 'diamond'
      B: 'beacon'
heart:
  material: 'apple'
