main: me.danilux.simplesteal.SimpleSteal
name: SimpleSteal
version: 1.0.0
author: Danilux
api-version: 1.21
permissions:
  ss.admin:
    default: op
    description: Perform SimpleSteal commands.
  ss.god:
    default: op
    description: Be immune to losing hearts.
  ss.immune:
    default: op
    description: Be immune to LifeSteal system.
  ss.doomed:
    default: op
    description: Be permanently banned from the LifeSteal.
